# Generated by Django 4.2.7 on 2026-08-06 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_alter_duepayment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_discount_flat_amount_order_discount_type'),
        ('suppliers', '0005_fix_payment_table'),
        ('products', '0006_product_no_stock_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('cng', 'CNG / Auto'), ('car', 'Car'), ('truck', 'Truck / Pickup'), ('other', 'Other')], default='bike', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10)),
                ('engine_number', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_km', models.PositiveIntegerField(blank=True, help_text='Only meaningful for used units', null=True)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, help_text='Asking price while in stock', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('sold', 'Sold')], db_index=True, default='in_stock', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='orders.order')),
                ('product', models.ForeignKey(help_text="The model this unit belongs to, e.g. 'Honda CB150R'", on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('papers_receipt', 'Papers Receipt'), ('registration', 'Registration'), ('tax_token', 'Tax Token'), ('fitness', 'Fitness Certificate'), ('insurance', 'Insurance'), ('delivery', 'Delivery Receipt'), ('nid', 'Buyer NID'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='vehicle_documents/%Y/%m/')),
                ('received_date', models.DateField(blank=True, help_text='When the shop received this paper', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'status'], name='vehicles_ve_user_id_1ae7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['product', 'status'], name='vehicles_ve_product_0a9a20_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('user', 'engine_number'), name='unique_engine_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('user', 'chassis_number'), name='unique_chassis_number_per_user'),
        ),
    ]
