# Generated by Django 4.2.7 on 2026-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_engine_number_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_chassis_number_per_user',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('engine_number', ''), _negated=True), fields=('user', 'engine_number'), name='unique_engine_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('chassis_number', ''), _negated=True), fields=('user', 'chassis_number'), name='unique_chassis_number_per_user'),
        ),
    ]
