# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_unique_engine_number_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(upload_to='vehicle_documents/%Y/%m/', validators=[core.uploads.validate_document]),
        ),
    ]
