# Generated by Django 5.1.4 on 2025-07-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstockmovement',
            name='reference_sale',
        ),
        migrations.DeleteModel(
            name='ProductSale',
        ),
    ]
