# Generated by Django 5.1.4 on 2025-07-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productstockmovement_reference_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product/Parts code (SKU, part number, etc.)', max_length=100, null=True),
        ),
    ]
