# Generated by Django 4.2.7 on 2025-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockmovement',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at the time of this stock movement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productstockmovement',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this stock movement (quantity * cost_per_unit)', max_digits=10, null=True),
        ),
    ]
