# Generated by Django 4.2.7 on 2025-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_cost_fields_to_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_stock_required',
            field=models.BooleanField(default=False, help_text="True if product doesn't require stock tracking (e.g., services, digital products)"),
        ),
    ]
