# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_no_stock_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to=products.models.product_photo_upload_path, validators=[core.uploads.validate_image]),
        ),
    ]
