# Generated by Django 5.1.4 on 2025-07-20 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Public API key for accessing user's product data", max_length=64, unique=True)),
                ('name', models.CharField(default='Default API Key', help_text='Human-readable name for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('requests_per_hour', models.PositiveIntegerField(default=1000, help_text='Maximum requests per hour for this API key')),
                ('requests_per_day', models.PositiveIntegerField(default=10000, help_text='Maximum requests per day for this API key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public API Key',
                'verbose_name_plural': 'Public API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='The API endpoint that was accessed', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('response_status', models.PositiveIntegerField(help_text='HTTP response status code')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='public_api.publicapikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='public_api__api_key_61d918_idx'), models.Index(fields=['timestamp'], name='public_api__timesta_d5c5e4_idx')],
            },
        ),
    ]
