"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# The real key lives in .env. The throwaway default exists only so a fresh
# checkout can run locally — in production a missing .env must stop the boot,
# not silently fall back to a key that is published in this file. Session
# cookies and password-reset tokens are signed with it.
SECRET_KEY = config("SECRET_KEY", default="" if not DEBUG else "django-insecure-local-only")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY is not set. Add it to backend/.env before starting the server."
    )

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,oxymanager.com,www.oxymanager.com",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# Application definition
INSTALLED_APPS = [
    # Jazzmin must precede django.contrib.admin so its templates win.
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_filters",
    "core",
    "suppliers",
    "products",
    "customers",
    "employees",
    "banking",
    "subscription",  # Added subscription app
    "orders",  # New orders app
    "online_store",  # Added online store app
    "public_api",  # Public API app for external access
    "notebook",  # Added notebook app for note management
    "vehicles",  # Serial-tracked vehicle units (bikes, CNGs, cars)
    "analytics",  # Cross-app business reporting
]

CORS_ALLOWED_ORIGINS = [
    "http://168.231.119.200",
    "http://168.231.119.200:3000",
    "https://168.231.119.200",
    "https://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://oxymanager.com",
    "https://oxymanager.com",
    "http://www.oxymanager.com",
    "https://www.oxymanager.com",
]

# Any localhost port is allowed in DEBUG so a second dev server (e.g. one
# started for testing) can reach the API. Production still uses the explicit
# CORS_ALLOWED_ORIGINS list above.
CORS_ALLOWED_ORIGIN_REGEXES = (
    [r"^http://(localhost|127\.0\.0\.1):\d+$"] if DEBUG else []
)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    "http://168.231.119.200",
    "https://168.231.119.200",
    "https://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://oxymanager.com",
    "https://oxymanager.com",
    "http://www.oxymanager.com",
    "https://www.oxymanager.com",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CSRFExemptTokenAuthentication",
        "public_api.authentication.PublicAPIKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardPagination",
    "PAGE_SIZE": 10,
    # Rate limiting to prevent API abuse and high CPU
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/minute",
        "user": "120/minute",
        # Password reset sends real SMS, so it gets its own tighter budget.
        "password_reset": "6/hour",
        "login": "10/min",
    },
}

# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG

# ── HTTPS hardening ───────────────────────────────────────────────────
# nginx terminates TLS and forwards X-Forwarded-Proto, so Django has to be told
# to trust that header — without it `request.is_secure()` is always False and
# the cookie/redirect settings below would misbehave.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # the SPA reads this token to send it back
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# nginx already redirects http → https; this is the backstop for any request
# that reaches Django over plain HTTP anyway. Off in development, where there
# is no certificate to redirect to.
SECURE_SSL_REDIRECT = not DEBUG

# Six months. Only meaningful in production, and deliberately not preloaded:
# preload is effectively irreversible and is the owner's decision, not a
# default.
if not DEBUG:
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 180
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SAMESITE = "Lax"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level templates — holds the branded admin shell
        # (templates/admin/base_site.html).
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # KPI/alert data for the admin dashboard (no-ops elsewhere).
                "core.admin_dashboard.dashboard_context",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("DB_NAME", default="oxm_user"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD", default="change-me-in-env"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# sms settings
API_SMS = config("API_SMS", default="")

# Internationalization
LANGUAGE_CODE = "en-us"
# The shop runs on Bangladesh time. On UTC, anything entered between midnight
# and 6am local fell on the previous day, so "আজ" showed yesterday's figures and
# an expense added at 4am never appeared in this month's report.
# USE_TZ stays on: timestamps are still stored as UTC, only interpretation moves.
TIME_ZONE = "Asia/Dhaka"
USE_I18N = True
USE_TZ = True

# ══════════════════════════════════════════════════════════════
# Jazzmin — admin UI. Menu labels are colloquial Bangla to match
# the app; model/app names themselves stay as Django knows them.
# ══════════════════════════════════════════════════════════════
JAZZMIN_SETTINGS = {
    "site_title": "OxyManager",
    "site_header": "OxyManager",
    "site_brand": "OxyManager",
    "site_logo": None,
    "login_logo": None,
    "site_icon": None,
    "welcome_sign": "OxyManager অ্যাডমিনে স্বাগতম",
    "copyright": "OxyManager",
    # Global search box at the top of the sidebar.
    "search_model": ["auth.User", "products.Product", "customers.Customer"],
    "user_avatar": None,

    # ── Top menu ──
    "topmenu_links": [
        {"name": "ড্যাশবোর্ড", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "সাইট দেখুন", "url": "/", "new_window": True},
        {"model": "auth.User"},
        {"app": "products"},
        {"app": "orders"},
    ],
    # ── User menu (top right) ──
    "usermenu_links": [
        {"name": "আমার প্রোফাইল", "url": "admin:auth_user_changelist"},
        {"model": "auth.user"},
    ],

    # ── Sidebar ──
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "products",
        "orders",
        "customers",
        "suppliers",
        "banking",
        "employees",
        "subscription",
        "online_store",
        "public_api",
        "notebook",
        "core",
    ],
    # Human labels for the app groups in the sidebar.
    "custom_links": {},
    "icons": {
        # auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "authtoken.tokenproxy": "fas fa-key",
        # products
        "products": "fas fa-boxes",
        "products.Product": "fas fa-box",
        "products.ProductVariant": "fas fa-layer-group",
        "products.ProductPhoto": "fas fa-image",
        "products.ProductStockMovement": "fas fa-exchange-alt",
        "products.Category": "fas fa-tags",
        "products.Brand": "fas fa-copyright",
        # orders
        "orders": "fas fa-shopping-cart",
        "orders.Order": "fas fa-receipt",
        "orders.OrderStockMovement": "fas fa-dolly",
        # customers
        "customers": "fas fa-user-friends",
        "customers.Customer": "fas fa-user-tie",
        "customers.DuePayment": "fas fa-hand-holding-usd",
        "customers.CustomerLevel": "fas fa-medal",
        "customers.CustomerGift": "fas fa-gift",
        "customers.CustomerAchievement": "fas fa-trophy",
        "customers.SMSLog": "fas fa-sms",
        # suppliers
        "suppliers": "fas fa-truck",
        "suppliers.Supplier": "fas fa-truck-loading",
        "suppliers.Purchase": "fas fa-file-invoice",
        "suppliers.Payment": "fas fa-money-check-alt",
        # banking
        "banking": "fas fa-university",
        "banking.BankAccount": "fas fa-piggy-bank",
        "banking.Transaction": "fas fa-exchange-alt",
        "banking.BankingPlan": "fas fa-clipboard-list",
        # employees
        "employees": "fas fa-id-badge",
        "employees.Employee": "fas fa-user-tie",
        "employees.SalaryRecord": "fas fa-money-bill-wave",
        "employees.Task": "fas fa-tasks",
        "employees.Incentive": "fas fa-award",
        "employees.IncentiveWithdrawal": "fas fa-hand-holding-usd",
        "employees.Document": "fas fa-file-alt",
        "employees.PaymentInformation": "fas fa-credit-card",
        # others
        "subscription": "fas fa-gem",
        "online_store": "fas fa-store",
        "online_store.OnlineProduct": "fas fa-box-open",
        "online_store.OnlineOrder": "fas fa-cart-arrow-down",
        "online_store.StoreSettings": "fas fa-cog",
        "public_api": "fas fa-plug",
        "public_api.PublicAPIKey": "fas fa-key",
        "public_api.APIKeyUsageLog": "fas fa-history",
        "notebook": "fas fa-book",
        "core": "fas fa-sliders-h",
        "core.CustomDomain": "fas fa-globe",
        "core.DNSRecord": "fas fa-network-wired",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── Change form: tabbed layout is what makes this feel like an app ──
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "show_ui_builder": False,
    # Brand tuning on top of Jazzmin's Bootstrap defaults (cyan + slate).
    "custom_css": "admin/css/oxm-jazzmin.css",
}

# Light chrome, Jazzmin's stock accents (no custom brand colour).
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations of static files
# Only add directories that exist to avoid warnings
STATICFILES_DIRS = []
static_dir = os.path.join(BASE_DIR, "static")
if os.path.exists(static_dir):
    STATICFILES_DIRS.append(static_dir)

# Static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Ensure media directories exist
os.makedirs(os.path.join(MEDIA_ROOT, "store_logos"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "banner_images"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "purchase_proofs"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "payment_proofs"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "products"), exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = config("FILE_UPLOAD_MAX_MEMORY_SIZE", default=10485760, cast=int)  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = config("DATA_UPLOAD_MAX_MEMORY_SIZE", default=10485760, cast=int)  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Allow file uploads
ALLOWED_UPLOAD_EXTENSIONS = [
    'jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx'
]

# Security settings for file uploads
SECURE_FILE_UPLOAD = True

# WhiteNoise configuration for static files in production
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    # Add cache control for static files
    WHITENOISE_MAX_AGE = 31536000  # 1 year
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "webp",
        "zip",
        "gz",
        "tgz",
        "bz2",
        "tbz",
        "xz",
        "br",
    ]
else:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Site URL for absolute URL construction in production
# Dynamically determine site URL based on environment
if DEBUG:
    SITE_URL = config("SITE_URL", default="http://localhost:8000")
else:
    # Production settings
    SITE_URL = config("SITE_URL", default="https://oxymanager.com")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ShurjoPay Settings
SP_USERNAME = config("SP_USERNAME", default="")
SP_PASSWORD = config("SP_PASSWORD", default="")
SP_ENDPOINT = config("SP_ENDPOINT", default="https://engine.shurjopayment.com")
# for live
if DEBUG:
    SP_RETURN = config("SP_RETURN", default="http://localhost:3000/dashboard/verify-payment")
    SP_CANCEL = config("SP_CANCEL", default="http://localhost:3000/dashboard/subscriptions")
else:
    SP_RETURN = config("SP_RETURN", default="https://oxymanager.com/dashboard/verify-payment")
    SP_CANCEL = config("SP_CANCEL", default="https://oxymanager.com/dashboard/subscriptions")
SP_PREFIX = "OXMPAY_"

# ── Email ─────────────────────────────────────────────────────────────
# Production hands mail to the local Postfix queue on 127.0.0.1:25. That
# matters for more than tidiness: an outbound SMTP handshake to a remote host
# can take seconds, and the password-reset request would block on it. Postfix
# accepts in milliseconds and owns the delivery, the retries and the bounce.
#
# Setting EMAIL_HOST in .env overrides this — point it at the domain's own
# mailbox provider (smtp.privateemail.com:587) and mail then leaves from an
# address the domain's SPF record already authorises, which is the single
# biggest thing that keeps it out of spam.
def _env(key, default="", cast=None):
    """Treat a blank .env value as absent.

    `EMAIL_PORT=` with nothing after it is how half the file is written, and
    decouple hands that empty string straight to `int()`.
    """
    raw = config(key, default="")
    raw = str(raw).strip()
    if raw == "":
        return default
    return cast(raw) if cast else raw


def _flag(key, default=False):
    raw = str(config(key, default="")).strip().lower()
    if raw == "":
        return default
    return raw in ("1", "true", "yes", "on")


EMAIL_BACKEND = _env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = _env("EMAIL_HOST", "127.0.0.1")
EMAIL_PORT = _env("EMAIL_PORT", 25, int)
EMAIL_HOST_USER = _env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _env("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _flag("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = _flag("EMAIL_USE_SSL", False)
# A short timeout so a stalled relay cannot hold a web worker open.
EMAIL_TIMEOUT = _env("EMAIL_TIMEOUT", 10, int)

DEFAULT_FROM_EMAIL = _env(
    "DEFAULT_FROM_EMAIL", "OxyManager <support@oxymanager.com>"
)
SERVER_EMAIL = _env("SERVER_EMAIL", "support@oxymanager.com")

