"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="django-insecure-change-me-in-production-12345678901234567890"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "168.231.119.200",
    "oxymanager.com",
    "www.oxymanager.com",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_filters",
    "core",
    "suppliers",
    "products",
    "customers",
    "employees",
    "banking",
    "subscription",  # Added subscription app
    "orders",  # New orders app
    "online_store",  # Added online store app
    "public_api",  # Public API app for external access
]

CORS_ALLOWED_ORIGINS = [
    "http://168.231.119.200",
    "http://168.231.119.200:3000",
    "https://168.231.119.200",
    "https://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://oxymanager.com",
    "https://oxymanager.com",
    "http://www.oxymanager.com",
    "https://www.oxymanager.com",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    "http://168.231.119.200",
    "https://168.231.119.200",
    "https://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://oxymanager.com",
    "https://oxymanager.com",
    "http://www.oxymanager.com",
    "https://www.oxymanager.com",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CSRFExemptTokenAuthentication",
        "public_api.authentication.PublicAPIKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("DB_NAME", default="oxm_user"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD", default="pgPass7431"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# sms settings
API_SMS = "SplZ3f60tlt69pkZAEc8WHk3MbHkGeLYtJ1jElCd"

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations of static files
# Only add directories that exist to avoid warnings
STATICFILES_DIRS = []
static_dir = os.path.join(BASE_DIR, "static")
if os.path.exists(static_dir):
    STATICFILES_DIRS.append(static_dir)

# Static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Ensure media directories exist
os.makedirs(os.path.join(MEDIA_ROOT, "store_logos"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "banner_images"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "purchase_proofs"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "payment_proofs"), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, "products"), exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = config("FILE_UPLOAD_MAX_MEMORY_SIZE", default=10485760, cast=int)  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = config("DATA_UPLOAD_MAX_MEMORY_SIZE", default=10485760, cast=int)  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# WhiteNoise configuration for static files in production
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    # Add cache control for static files
    WHITENOISE_MAX_AGE = 31536000  # 1 year
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "webp",
        "zip",
        "gz",
        "tgz",
        "bz2",
        "tbz",
        "xz",
        "br",
    ]
else:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Site URL for absolute URL construction in production
# Dynamically determine site URL based on environment
if DEBUG:
    SITE_URL = config("SITE_URL", default="http://localhost:8000")
else:
    # Production settings
    SITE_URL = config("SITE_URL", default="https://oxymanager.com")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ShurjoPay Settings
SP_USERNAME = "lyriczsoft"
SP_PASSWORD = "lyrikskdzprvz&ud"
SP_ENDPOINT = "https://engine.shurjopayment.com"
# for live
SP_RETURN = "http://oxymanager.com/dashboard/verify-payment"
SP_CANCEL = "http://oxymanager.com/dashboard/subscriptions"
# for development
# SP_RETURN = "http://localhost:3000/dashboard/verify-payment"
# SP_CANCEL = "http://localhost:3000/dashboard/subscriptions"
SP_PREFIX = "OXMPAY_"
