# Generated by Django 4.2.7 on 2025-06-30 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_paymentmethod_brand'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlevel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerlevel',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customer_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerlevel',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='customerlevel',
            unique_together={('customer', 'level', 'is_current')},
        ),
    ]
