# Generated by Django 4.2.7 on 2025-06-29 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_level'),  # Need Level model
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='assigned_customer_levels', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='customer_levels', to='customers.customer')),
                ('level', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='customerlevel',
            unique_together={('customer', 'level', 'is_current')},
        ),
    ]
