# Generated by Django 4.2.7 on 2025-06-29 16:40

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlevel',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='customerlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
