# Generated by Django 5.1.4 on 2025-07-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerlevel_created_at_customerlevel_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
