# Generated by Django 5.1.4 on 2025-07-09 09:48

from django.db import migrations


def cleanup_orphaned_order_references(apps, schema_editor):
    """
    Clean up orphaned order references in DuePayment and Transaction models
    before the schema migration removes the old Order model.
    """
    # Get model classes
    DuePayment = apps.get_model("customers", "DuePayment")
    Transaction = apps.get_model("customers", "Transaction")

    # Set orphaned order references to NULL in DuePayment
    orphaned_due_payments = DuePayment.objects.filter(order__isnull=False)
    updated_due_payments = 0
    for due_payment in orphaned_due_payments:
        try:
            # Check if the referenced order exists in the new orders app
            # Since we can't easily check cross-app during migration,
            # we'll just set all order references to NULL for safety
            due_payment.order = None
            due_payment.save()
            updated_due_payments += 1
        except Exception:
            # If there's any issue, just set to NULL
            due_payment.order = None
            due_payment.save()
            updated_due_payments += 1

    # Set orphaned order references to NULL in Transaction
    orphaned_transactions = Transaction.objects.filter(order__isnull=False)
    updated_transactions = 0
    for transaction in orphaned_transactions:
        try:
            # Set all order references to NULL for safety
            transaction.order = None
            transaction.save()
            updated_transactions += 1
        except Exception:
            # If there's any issue, just set to NULL
            transaction.order = None
            transaction.save()
            updated_transactions += 1

    print(f"Cleaned up {updated_due_payments} DuePayment records")
    print(f"Cleaned up {updated_transactions} Transaction records")


def reverse_cleanup_orphaned_order_references(apps, schema_editor):
    """
    Reverse migration - nothing to do since we only nullified references
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_remove_order_customer_remove_order_user"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_order_references,
            reverse_cleanup_orphaned_order_references,
        ),
    ]
