# Generated by Django 5.1.4 on 2025-07-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_auto_20250709_1548"),
        ("orders", "0001_initial"),
    ]

    operations = [
        # First, update foreign key references to point to the new orders app
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="duepayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="due_payments",
                to="orders.order",
            ),
        ),
        # Remove fields that reference orders from other models
        migrations.RemoveField(
            model_name="customergift",
            name="used_in_order",
        ),
        # Clean up OrderItem constraints before removing fields
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=None,
        ),
        # Remove OrderItem fields
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant",
        ),
        # Finally, delete the models
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
