# Generated by Django 4.2.7 on 2025-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_unique_together_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
