# Generated by Django 4.2.7 on 2025-08-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_transaction_verified_by'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS banking_bankingsettings CASCADE;",
            reverse_sql="-- No reverse SQL needed",
            hints={'drop_table': True}
        ),
    ]
