# Generated by Django 5.0.2 on 2025-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bankingplan_userbankingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, help_text='10-digit unique account number', max_length=10, null=True, unique=True),
        ),
    ]
