# Generated by Django 4.2.7 on 2026-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bankaccount_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('internet', 'Internet / Phone'), ('salary', 'Salary'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('tax', 'Tax / Fees'), ('other', 'Other')], default='', help_text='Cost bucket, used by the monthly expense report.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nature',
            field=models.CharField(blank=True, choices=[('expense', 'Expense'), ('payment', 'Payment'), ('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], default='', help_text='What this money was for. Blank on rows created before this existed.', max_length=20),
        ),
    ]
