# Generated by Django 4.2.7 on 2026-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_loan_loanpayment_loan_banking_loa_user_id_b390b4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Cost bucket for the monthly expense report. Free text rather than a fixed choice list — CATEGORY_CHOICES are only the suggestions the UI offers, and a shop can name its own.', max_length=50),
        ),
    ]
