# Generated by Django 4.2.7 on 2026-08-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(blank=True, choices=[('expense', 'Expense'), ('payment', 'Payment'), ('income', 'Income'), ('withdrawal', 'Withdrawal'), ('other', 'Other')], default='', help_text='What this money was for. Blank on rows created before this existed.', max_length=20),
        ),
    ]
