# Generated by Django 4.2.7 on 2026-08-06 22:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0011_alter_transaction_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. অফিস ভাড়া', max_length=150)),
                ('category', models.CharField(default='rent', help_text='Cost bucket, matching Transaction.category', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month it falls due (1-31)')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Which account it is paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_costs', to='banking.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecurringCostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month being paid for')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='banking.recurringcost')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payment', to='banking.transaction')),
            ],
            options={
                'ordering': ['-period', '-id'],
                'unique_together': {('cost', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='recurringcost',
            index=models.Index(fields=['user', 'is_active'], name='banking_rec_user_id_3d07d0_idx'),
        ),
    ]
