# Generated by Django 4.2.7 on 2026-08-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_recurringcost_recurringcostpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcostpayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Scan or photo of the money receipt', null=True, upload_to='rent_receipts/%Y/%m/'),
        ),
    ]
