# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_recurringcostpayment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringcostpayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Scan or photo of the money receipt', null=True, upload_to='rent_receipts/%Y/%m/', validators=[core.uploads.validate_document]),
        ),
    ]
