# Generated by Django 4.2.7 on 2026-08-07 08:58

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_alter_recurringcostpayment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Scan or photo of the installment receipt', null=True, upload_to='loan_receipts/%Y/%m/', validators=[core.uploads.validate_document]),
        ),
    ]
