# Generated by Django 4.2.7 on 2026-08-08 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('trade_license', 'ট্রেড লাইসেন্স'), ('tin', 'টিন সার্টিফিকেট'), ('vat', 'ভ্যাট / বিআইএন'), ('bank', 'ব্যাংকের কাগজ'), ('rent_agreement', 'দোকান ভাড়ার চুক্তি'), ('insurance', 'ইনস্যুরেন্স'), ('fire_license', 'ফায়ার লাইসেন্স'), ('nid', 'এনআইডি / পরিচয়পত্র'), ('partnership', 'পার্টনারশিপ দলিল'), ('utility', 'বিদ্যুৎ / গ্যাস / পানির বিল'), ('tax_return', 'আয়কর রিটার্ন'), ('other', 'অন্যান্য')], db_index=True, default='other', max_length=30)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Licence / certificate number printed on the paper', max_length=120)),
                ('issued_by', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_pinned', models.BooleanField(default=False, help_text='Keep at the top of the list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='The login that uploaded it — may be a staff account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_important_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'জরুরি কাগজ',
                'verbose_name_plural': 'জরুরি কাগজপত্র',
                'ordering': ['-is_pinned', models.OrderBy(models.F('expiry_date'), nulls_last=True), '-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='documents_i_owner_i_8fba19_idx'), models.Index(fields=['owner', 'expiry_date'], name='documents_i_owner_i_63dd82_idx')],
            },
        ),
    ]
