# Generated by Django 4.2.7 on 2025-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_incentivewithdrawal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['employee', '-date_awarded'], name='employees_i_employe_1da070_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['employee', 'status'], name='employees_i_employe_4ece9f_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['status', '-date_awarded'], name='employees_i_status_54060f_idx'),
        ),
        migrations.AddIndex(
            model_name='incentivewithdrawal',
            index=models.Index(fields=['employee', '-withdrawal_date'], name='employees_i_employe_ee1020_idx'),
        ),
    ]
