# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_unique_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='employee_documents/', validators=[core.uploads.validate_document]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', validators=[core.uploads.validate_image]),
        ),
    ]
