# Generated by Django 4.2.7 on 2026-08-07 10:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_loanpayment_receipt'),
        ('employees', '0007_employeeaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('kind', models.CharField(choices=[('advance', 'Advance'), ('salary', 'Salary')], default='salary', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile', 'Mobile Banking')], default='cash', max_length=10)),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employees.employee')),
                ('salary_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='employees.salaryrecord')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment', to='banking.transaction')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
                'indexes': [models.Index(fields=['employee', 'paid_on'], name='employees_s_employe_0c75be_idx')],
            },
        ),
    ]
