# Generated by Django 4.2.7 on 2026-08-07 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='date_awarded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incentivewithdrawal',
            name='withdrawal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
