# Generated by Django 4.2.7 on 2025-06-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=models.TextField(help_text='Products purchased (comma-separated)'),
        ),
    ]
