# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_fix_payment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/', validators=[core.uploads.validate_document]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='purchase_proofs/', validators=[core.uploads.validate_document]),
        ),
    ]
