# Generated by Django 5.0.2 on 2025-06-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersettings'),
    ]

    operations = [
    ]
