# Generated by Django 5.0.2 on 2025-06-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=5),
        ),
    ]
