# Generated by Django 5.0.2 on 2025-06-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usersettings_language'),
    ]

    operations = [
    ]
