# Generated by Django 5.0.2 on 2025-06-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('orders', 'Order Count'), ('amount', 'Purchase Amount')], max_length=10)),
                ('value', models.PositiveIntegerField(help_text='Target value (number of orders or amount in dollars)')),
                ('points', models.PositiveIntegerField(help_text='Points awarded when achievement is earned')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['type', 'value'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
