# Generated by Django 4.2.7 on 2025-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentmethod_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol based on selected currency', max_length=5),
        ),
    ]
