# Generated by Django 4.2.7 on 2025-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_address_userprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
