# Generated by Django 4.2.7 on 2025-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_city_userprofile_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_balance',
            field=models.IntegerField(default=0),
        ),
    ]
