# Generated by Django 4.2.7 on 2025-07-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_userprofile_balance_userprofile_sms_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Custom domain (e.g., example.com)', max_length=255, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Optional subdomain prefix', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A Record'), ('AAAA', 'AAAA Record'), ('CNAME', 'CNAME Record'), ('MX', 'MX Record'), ('TXT', 'TXT Record'), ('NS', 'NS Record')], max_length=10)),
                ('name', models.CharField(help_text='DNS record name (e.g., @, www, mail)', max_length=255)),
                ('value', models.TextField(help_text='DNS record value')),
                ('ttl', models.IntegerField(default=3600, help_text='Time to live in seconds')),
                ('priority', models.IntegerField(blank=True, help_text='Priority for MX records', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='core.customdomain')),
            ],
            options={
                'verbose_name': 'DNS Record',
                'verbose_name_plural': 'DNS Records',
                'ordering': ['record_type', 'name'],
                'unique_together': {('custom_domain', 'record_type', 'name')},
            },
        ),
    ]
