# Generated by Django 4.2.7 on 2025-07-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_change_domain_default_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdomain',
            name='subdomain',
        ),
    ]
