# Generated by Django 4.2.7 on 2026-08-07 08:12

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', validators=[core.uploads.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', validators=[core.uploads.validate_image]),
        ),
    ]
