# Generated by Django 4.2.7 on 2026-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='closed_days',
            field=models.JSONField(blank=True, default=list, help_text='Weekdays the shop is closed: 0=Mon … 6=Sun'),
        ),
    ]
