# Generated by Django 5.0 on 2026-02-21 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooktag',
            name='name',
            field=models.CharField(help_text='Tag name', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='notebooktag',
            unique_together={('created_by', 'name')},
        ),
    ]
